### ISSUE TITLE
Invalid escaping if stories.yml args contain top-level object.

### ISSUE THREAD

**Issue by mikemiles86** [Lullabot/storybook-drupal-addon#20]
When creating a `*.stories.yml` file for a component if an argument is an object and it is not contained within an items array, then the whole object is escaped and treated as a string. This prevents the "cl_server" module from correctly decoding it and passing the arguments to the twig template.

This seems to be an issue from this plugin not correctly escaping and encoding the arguments from the *.stories.yml file.

### Twig template (mycomponent.twig.html)
```
<h1>{{ title }}</h1>
{% if cta.url %}
 <a href="{{ cta.url }}" target="{{ cta.target }}">{{ cta.text }}</a>
{% endif %}
```

### Stories (mycomponent.stories.yml)
```
title: components/MyComponent
stories:
  - name: Default
    args:
      title: "Component Example"
      cta:
        url: "https://www.example.com"
        text: "Learn More"
        target: "_blank" 
```

### Request
*Example of the request sent to the cl_server endpoint:*
```
https://www.mywebsite.com/_cl_server?_storyFileName=.%2Fweb%2Fthemes%2Fcustom%2Fmytheme%2Fcomponents%2Fmycomponent%2Fmycomponent.stories.yml&_drupalTheme=mytheme&_params=eyJ0aXRsZSI6ICJDb21wb25lbnQgRXhhbXBsZSIsImN0YSI6ICJ7XCJ1cmxcIjpcImh0dHBzOi8vd3d3LmV4YW1wbGUuY29tL1wiLFwidGV4dFwiOlwiTGVhcm4gTW9yZVwiLFwidGFyZ2V0XCI6XCJfYmxhbmtcIn0ifQ==
```
*Decoded request:*
What the decoded params are decoded as:
```
{"title": "Component Example","cta": "{\"url\":\"https://www.example.com/\",\"text\":\"Learn More\",\"target\":\"_blank\"}"}
```

*Expected request:*
What the decoded params should be decoded as:
```
{"title": "Component Example","cta":{"url":"https://www.example.com/","text":"Learn More","target":"_blank"}}
```
