### ISSUE TITLE
How to add some Documentation to a *.stories.yml file

### ISSUE THREAD

**Issue by theodorosploumis** [Lullabot/storybook-drupal-addon#34]
I am trying to add some Documentation to a *.stories.yml file.

But the DocsPage is never shown on the Docs tab in Storybook. Is the addon [docs](https://storybook.js.org/addons/@storybook/addon-docs) supported or since we use a "server" Storybook framework this is not possible?

My setup:

- cl_server: 2.x-dev
- drupal: 10.1.0-alpha1
- Storybook: 7.0.20
- @lullabot/storybook-drupal-addon: 1.0.27

**Comment by idiazroncero** [comment]
Hello @theodorosploumis 

I've been able to add docs to components using Storybook 7 and CL Server, but still struggling to make it work with [AutoDocs](https://storybook.js.org/docs/html/writing-docs/autodocs)

Here is an example of `button.mdx` inside the component folder

```mdx
{/* Button.mdx */}

import { Canvas, Meta, Primary, Title, Subtitle } from '@storybook/blocks';
import * as ButtonStories from './button.stories.yml';

<Meta of={ButtonStories} name="Documentation"/>

<Title />
<Subtitle />

Bootstrap includes several predefined button styles, each serving its own semantic purpose, with a few extras thrown in for more control.

## Default buttons

<Primary />

<Canvas of={ButtonStories.Default_button} />

The .btn classes are designed to be used with the `button` element. However, you can also use these classes on `a` or `input` elements (though some browsers may apply a slightly different rendering).

When using button classes on `a` elements that are used to trigger in-page functionality (like collapsing content), rather than linking to new pages or sections within the current page, these links should be given a role="button" to appropriately convey their purpose to assistive technologies such as screen readers.

## Outline variants

<Canvas of={ButtonStories.Outlined_button} />

```

Notice that `import * as ButtonStories from './button.stories.yml';` is mandatory as it is used by the component `<Meta of={ButtonStories} name="Documentation"/>`to be able to put the docs in the sidebar alongside the correct component.

Another option is to skip the` import` and use a title:

`<Meta title="/path/to/your/component" name="Custom docs"/>`, but the Meta component is very relevant in order to tell Storybook where to render the docs or to wich component does it belong to.

More info [here](https://storybook.js.org/docs/react/api/doc-block-meta)

And, of course, the `main.js` should parse the `*.mdx` files:

```js
const config = {
  stories: [
    "../web/themes/**/*.mdx",
    "../web/themes/**/*.stories.@(json|yml)",
    "../web/modules/**/*.mdx",
    "../web/modules/**/*.stories.@(json|yml)",
  ],
}
```

**Comment by idiazroncero** [comment]
I will try to put all this together on the official docs, see [this issue](https://www.drupal.org/project/cl_server/issues/3366660#comment-15103176)

**Comment by theodorosploumis** [comment]
@idiazroncero Can you paste the `button.stories.yml` here? I am missing some tags and I am not sure what they mean on the yml file (eg the `<Primary />`).
Thanks!

**Comment by idiazroncero** [comment]
I'm just working on documenting how to map `*.stories.yml` values to Storybook [Doc block elements](https://storybook.js.org/docs/react/writing-docs/doc-blocks). This is a rather complex `button.stories.yml` i'm using, please note I'm deliberately "overusing" all possible properties here and your example could and even should be less verbose:

```yml
title: Radix/Button
tags:
  - autodocs

parameters:
  componentSubtitle: Bootstrap 5 Button Component
  docs:
    description:
      component: Buttons express actions the user can make on the page

argTypes:
  type:
    name: type
    type:
      name: 'string'
      required: true
    description: The button type
    table:
      category: Styling
      type:
        summary: string
        # detail: Bootstrap includes several predefined button styles, each serving its own semantic purpose, with a few extras thrown in for more control.
      defaultValue:
        summary: primary
        # detail: Available styles are predefined by Bootstrap 5 and can be extended.
    control:
      type: radio
    options:
      Primary: primary
      Secondary: secondary
      Success: success
      Danger: danger
      Warning: warning
      Info: info
      Dark: dark
      Light: light
      Link: link

  outline:
    type: boolean
    name: outline
    description: Wether the button renders with an outline instead of a solid background.
    table:
      category: Styling
      type:
        summary: boolean
      defaultValue:
        summary: false

  button_content:
    type: string
    name: button_content
    description: A slot for the button content. It can take a simple string or valid twig markup.
    table:
      category: Content
      type:
        summary: string

  tag:
    type: string
    name: tag
    description: The HTML element that gets rendered as a button. If Link, `url` prop is required
    table:
      category: Behavior
      type:
        summary: string
      defaultValue:
        summary: button
    options:
      Button: button
      Link: a
      Input: input
    control: radio

  url:
    type: string
    name: url
    description: A URL for tag:Link elements.
    table:
      category: Behavior
      type:
        summary: string

  disabled:
    type: boolean
    name: disabled
    description: Wether the button is disabled
    table:
      category: Behavior
      type:
        summary: boolean
      defaultValue:
        summary: false

  # attributes:
  #   type: \Drupal\Core\Template\Attribute
  #   name: attributes
  #   description: The Drupal Attributes object
  #   table:
  #     category: Drupal
  #     type:
  #       summary: \Drupal\Core\Template\Attribute

stories:
  - name: Default button
    primary: true
    args:
      type: primary
      outline: false
      tag: button
      disabled: false
      button_content: Default Button
    parameters:
      docs:
        description:
          story: 'By defaut, the button is a solid, `<button>` HTML element. Use the props to turn it into a link or input, disable it, change its color or its styling to outline and more.'
  - name: Outlined button
    args:
      type: primary
      tag: button
      outline: true
      disabled: false
      button_content: Outline Button
  - name: Linked button
    args:
      type: primary
      outline: false
      tag: a
      url: https://canamo.net
      disabled: false
      button_content: Link as a button
  - name: Disabled input button
    args:
      type: primary
      outline: false
      tag: input
      disabled: true
      button_content: Link as a button
```

With this `button.mdx` :+1: 

```mdx
{/* DocumentationTemplate.mdx */}

import { ArgTypes, Meta, Title, Subtitle, Description, Primary } from '@storybook/blocks';
import * as ButtonStories from './button.stories.yml';

{/*
  * 👇 The isTemplate property is required to tell Storybook that this is a template
  * See https://storybook.js.org/docs/react/api/doc-block-meta
  * to learn how to use
*/}

<Meta of={ButtonStories} />

<Title />
<Subtitle />
<Description of={ButtonStories}/>
<Description of={ButtonStories.Default_button}/>

# Default implementation

<Primary />

## Inputs

The component accepts the following inputs (props):

<ArgTypes of={ButtonStories.Default_button}/>
```

(and of course the component defined on its `button.twig` and `button.component.yml`

I get this:

![screencapture-localhost-6006-2023-06-15-14_20_33](https://github.com/Lullabot/storybook-drupal-addon/assets/3958741/e746d85a-6f57-4474-bff4-633ba1504913)
